name: Invariant testing CI

on:
  push:
    branches: [ "main", "merge_testing_analyzer" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
    - name: Setup dependencies
      run: |
        cd invariant
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/testing" >> $GITHUB_ENV
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.INVARIANT_TESTING_OPENAI_KEY }}
      run: |
        cd testing
        poetry run pytest --cov=invariant --cov-report=term --cov-fail-under=60 -s -vv tests
